/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Message } from "wow-mum-look-no-hands";
export namespace Components {
    interface WowMumLoader {
        "loadMessagesFromString": (json: string) => Promise<void>;
        "loadMessagesFromUrl": (url: string) => Promise<void>;
        "messageData": string;
        "messageDataUrl": string;
        "setMessages": (messages: Message[]) => Promise<void>;
        "showtime": () => Promise<void>;
    }
}
declare global {
    interface HTMLWowMumLoaderElement extends Components.WowMumLoader, HTMLStencilElement {
    }
    var HTMLWowMumLoaderElement: {
        prototype: HTMLWowMumLoaderElement;
        new (): HTMLWowMumLoaderElement;
    };
    interface HTMLElementTagNameMap {
        "wow-mum-loader": HTMLWowMumLoaderElement;
    }
}
declare namespace LocalJSX {
    interface WowMumLoader {
        "messageData"?: string;
        "messageDataUrl"?: string;
    }
    interface IntrinsicElements {
        "wow-mum-loader": WowMumLoader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wow-mum-loader": LocalJSX.WowMumLoader & JSXBase.HTMLAttributes<HTMLWowMumLoaderElement>;
        }
    }
}
